
maker_exhibits_holdover: false
maker_exhibits_show_location: false
test_text: "my settings text"

call_for_makers_open: true 

#homepage settings
featured_makers: false
event_shirt_promo: false
explore_meet_makers: false

footer_ad: true
footer_ad_url: /attend


