
maker_exhibits_holdover: false
maker_exhibits_show_location: false
test_text: "my settings text"

call_for_makers_open: false

#homepage settings
featured_makers: true
event_shirt_promo: false
explore_meet_makers: true

footer_ad: true
footer_ad_url: /attend/


